project:
  type: website

website:
  title: "Agent Notes"
  navbar:
    logo: assets/images/logo_v1.png
    right:
      - href: index.qmd
        text: Now
      - text: Tutorials
        menu:
          - href: projects/dspy/notebooks/copro-tutorial.html
            text: COPRO
  page-footer:
    center: "View this website source code on [GitHub](https://github.com/WSJUSA/agentnotes)"

format:
  html:
    toc: true
    include-in-header: _quarto/custom-header.html
    theme:
      light: journal
      dark: darkly


execute:
  echo: true
  eval: false
  cache: false