[build]
  command = "curl -L https://quarto.org/download/latest/quarto-linux-amd64.tar.gz | tar -xz -C /opt/build && mv /opt/build/quarto-* /opt/build/quarto && export PATH=$PATH:/opt/build/quarto/bin && git submodule update --init --recursive && /opt/build/quarto/bin/quarto render"
  publish = "/opt/build/repo/docs"